const express = require('express');
let router = express.Router();

const attendanceAggregate = require('../bll/attendanceManagement/attendanceAggregate');
const attendanceSubmission = require('../bll/attendanceManagement/attendanceSubmission');
const attendanceStatus = require('../bll/attendanceManagement/attendanceStatus');
/**
 * @swagger
 * /attendance/submission:
 *  post:
 *    tags:
 *      - Attendance Management
 *    summary: Record attendance as either late or punctual
 *    description: Based on the startTime and lateTime we will record the attendance status in the database
 *    consumes:
 *      - application/json
 *    produces:
 *      - application/json
 *    parameters:
 *      - in: body
 *        name: attendance submission body
 *        description: Document format
 *        schema:
 *          type: object
 *          required:
 *            - userId
 *            - lessonId
 *          properties:
 *            userId: 
 *              type: string
 *              example: X12345
 *              description: userId that was used to create account
 *            lessonId:
 *              type: string
 *              example: 5e50df1fe2828024f8a5dd66
 *              description: lessonId that was created by MongoDB
 *            seatingPlan:
 *              type: array
 *              example: [1,4,2,5,6,8,7,3]
 *    responses:
 *      200:
 *        description: attendance status updated
 *      409:
 *        description: Ids don;t exist or invalid ID
 *      500:
 *        description: Database or server error
 */ 
router.post('/attendance/submission', attendanceSubmission.attendanceSubmission);

/**
 * @swagger
 * /attendance/status:
 *  get:
 *    tags:
 *      - Attendance Management
 *    summary: Check if attendance can be filled or check past records of attendance
 *    description: Check if attendance can be filled or check past records of attendance based on lessonId. Time is used to gauge status
 *    consumes:
 *      - application/json
 *    produces:
 *      - application/json
 *    parameters:
 *      - in: query
 *        name: lessonId
 *        schema:
 *          type: string
 *          example: 5e50214a16e61201e8f6812a
 *        description: lesson ID that was generated by MongoDB
 *      - in: query
 *        name: userId
 *        schema:
 *          type: string
 *          example: X12345
 *    responses:
 *      200:
 *        description: Returns lesson status and attendance if applicable
 *      409:
 *        description: Lesson does not exist
 *      500:
 *        description: Database or server error
 */ 
router.get('/attendance/status', attendanceStatus.attendanceStatus);

/**
 * @swagger
 * /attendance/aggregate:
 *  get:
 *    tags:
 *      - Attendance Management
 *    summary: Look up the database and get the status of student's status
 *    description: Aggregate attendance into punctual, late or absent
 *    consumes:
 *      - application/json
 *    produces:
 *      - application/json
 *    parameters:
 *      - in: query
 *        name: lessonId
 *        schema:
 *          type: string
 *          example: 5e50214a16e61201e8f6812a
 *        description: lesson ID that was generated by MongoDB
 *    responses:
 *      200:
 *        description: Returns total, punctual, late and absent numbers
 *      409:
 *        description: Lesson does not exist
 *      500:
 *        description: Database or server error
 */
router.get('/attendance/aggregate', attendanceAggregate.attendanceAggregate);


module.exports = router;